### ISSUE TITLE
Using jail with reason removes needed part of message

### ISSUE THREAD

**Issue by zmontgo** [benjaminbhollon/finriq#51]
.jail [user] [message] replies "Puts [user] [reason]" Should return "Puts [user] in jail for [reason]"

**Comment by acheong08** [comment]
@zmontgo That isn't the issue

**Comment by acheong08** [comment]
It does .jail puts [userinput] in jail

**Comment by acheong08** [comment]
if userinput includes user, it does @[user]

**Comment by acheong08** [comment]
But userinput is can include a message after @
